sudo: required
service:
  - docker

before_install:
  - docker build -t vkas288/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vkas288/complex-test npm run test

after_success:
  - docker build -t vkas288/complex-client ./client
  - docker build -t vkas288/complex-api ./api
  - docker build -t vkas288/complex-nginx ./nginx
  - docker build -t vkas288/complex-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # push images to docker hub
  - docker push vkas288/complex-client
  - docker push vkas288/complex-api
  - docker push vkas288/complex-nginx
  - docker push vkas288/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-east-1-322749254772
  bucket_path: complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY